### ISSUE TITLE
Increase space ruin budget

### ISSUE THREAD

**Issue by JohnTheAutist** [not-a-furry/vmstation#79]
The variable `Space_Budget 16` in game_options.txt should be increased. Would help with more spawners spawning. I almost never see the syndicate listening base spawn for example. Also there isn't much of an advantage to keeping it low since space ruin loot isn't as good as lavaland loot. Maybe increase it to 30-40 (lavaland is 60 for reference). I don't see any harm with jacking the number way up.

related https://github.com/not-a-furry/vmstation/pull/78

**Comment by sperky7933** [comment]
yeah sure i think its dumb that its limited, will boost to 40 on server but not repo
